Repository thoth-station/micropipenv, pull requests merged in 2020-08, with the labels that each got.

#115 Test against pip 20.2.1
  micropipenv.py
Labels: approved, size/XS

#117 Enable Thoth integration for automatic pip updates
  .thoth.yaml
  requirements.in
  requirements.txt
Labels: size/M

#118 Test against pip==20.2.2
  micropipenv.py
Labels: approved, size/XS

#119 Remove unused imports from setup.py
  setup.py
Labels: approved, size/XS

#122 Test micropipenv against pip from the master branch
  .travis.yml
  tests/conftest.py
  tox.ini
Labels: approved, size/S

#127 Automatic update of dependency pip from 20.1.1 to None
  requirements.txt
Labels: approved, bot, size/S, update
