Repository thoth-station/micropipenv, pull requests merged in 2020-02, with the labels that each got.

#2 Minor fixes in README file
  README.rst
Labels: approved, size/XS

#4 Add templates for releases
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#6 Add ability to propagate arguments to pip options
  README.rst
  micropipenv.py
  tests/test_micropipenv.py
Labels: approved, size/S

#7 State dev-requirements.{in,txt} in README
  README.rst
Labels: approved, size/XS

#5 Fix tests in test suite
  tests/test_micropipenv.py
Labels: approved, size/XS

#8 Add URL to project
  setup.py
Labels: size/XS

#9 Remove unused function
  micropipenv.py
Labels: size/S

#11 Run pip install with --no-deps
  micropipenv.py
Labels: approved, size/XS

#14 Fix testsuite - the hash computation has been fixed
  tests/test_micropipenv.py
Labels: approved, size/XS

#13 Install dependencies iterativelly with a fallback
  micropipenv.py
Labels: approved, size/M

#15 Updated zuul configuration file for the repo
  .zuul.yaml
Labels: approved, size/XS

#21 Add period into the docstring
  micropipenv.py
Labels: approved, size/XS
