Repository thoth-station/micropipenv, pull requests merged in 2020-03, with the labels that each got.

#31 Adjust project description
  setup.py
Labels: approved

#30 Add tests for Poetry requirements parsing
  micropipenv.py
  tests/data/parse/pip-tools/Pipfile.lock
  tests/data/parse/pipenv/Pipfile
  tests/data/parse/pipenv/Pipfile.lock
  tests/data/parse/poetry2/poetry.lock
  tests/data/parse/poetry2/pyproject.toml
  tests/test_micropipenv.py
Labels: approved

#32 Document example usage in the README file
  README.rst
Labels: approved, size/M

#34 Change discovery order of installation method
  README.rst
  micropipenv.py
Labels: approved

#35 Fix installation from git
  micropipenv.py
Labels: approved, size/XS

#39 Include LICENSE file via MANIFEST.in instead of data_files in setup.py.
  MANIFEST.in
  setup.py
Labels: approved

#40 Fix requirements creation when Git version of a package is used
  micropipenv.py
Labels: approved

#47 Implement tox to test micropipenv with all supported Pythons
  setup.py
  tox.ini
Labels: approved
