Repository thoth-station/micropipenv, pull requests merged in 2020-06, with the labels that each got.

#67 Revisit setup.py structure
  setup.py
Labels: size/S

#71 Relicensing to LGPL v3+
  LICENSE
  LICENSE-GPL
  LICENSE-LGPL
  MANIFEST.in
  micropipenv.py
  setup.py
Labels: size/XXL

#73 Remove Thoth's configuration file
  .thoth.yaml
Labels: size/S

#72 Run tests with multiple versions of pip
  tests/test_micropipenv.py
  tox.ini
Labels: approved, size/S

#76 Fix automatic selection of the installation method
  micropipenv.py
Labels: size/M

#70 Version 0.2.0
  micropipenv.py
Labels: size/XS

#78 Add a note about available RPM packages in Fedora
  README.rst
Labels: approved, size/XS

#79 Do not suggest thoth-pipenv anymore
  README.rst
Labels: approved, size/XS

#81 Fix license declared in setup.py
  setup.py
Labels: approved, size/XS

#82 Add licensing and copyright notice
  README.rst
Labels: approved, size/S

#83 Provide LICENSE file with LGPL v3+ for GitHub
  LICENSE
Labels: approved, size/L

#84 Fix OrderedDict initialization
  micropipenv.py
Labels: size/S

#85 Extend documentation string
  micropipenv.py
Labels: size/S

#87 Initial Travis CI configuration
  .travis.yml
Labels: approved, size/S

#89 Use Python as Travis CI language
  .travis.yml
Labels: size/XS

#90 Add Travis CI badge
  README.rst
Labels: size/S

#88 Save traversals when requirements file is already discovered
  micropipenv.py
Labels: size/XS

#86 Raise an appropriate exception for unsupported VCS installations
  micropipenv.py
  tests/data/install/requirements_svn/requirements.txt
  tests/test_micropipenv.py
Labels: size/S

#92 Add pip>=19.2<20 support
  micropipenv.py
Labels: size/S

#91 Extend the list of supported pip versions
  .travis.yml
  tests/test_micropipenv.py
  tox.ini
Labels: approved, size/M

#93 Run CI for the most latest pip
  .travis.yml
  tests/test_micropipenv.py
  tox.ini
Labels: size/S

#94 Version 0.3.0
  CHANGELOG.md
  micropipenv.py
Labels: size/M, size/S, size/XS

#96 Fix pip's latest CI test
  tox.ini
Labels: size/XS

#97 Use fedorapython/fedora-python-tox container image in CI
  .travis.yml
Labels: approved, size/XS
