Repository thoth-station/micropipenv, pull requests merged in 2020-07, with the labels that each got.

#98 Pytoml support
  .travis.yml
  micropipenv.py
  tests/test_micropipenv.py
  tox.ini
Labels: approved

#100 Add support for file spec requirements
  micropipenv.py
  tests/data/install/pipenv_file/Pipfile.lock
  tests/test_micropipenv.py
Labels: approved, size/M

#104 Be more descriptive in the unpinned warning message produced
  micropipenv.py
Labels: size/XS

#105 Implement conditional test skip based on pip version
  tests/conftest.py
  tests/test_micropipenv.py
  tox.ini
Labels: size/M

#103 Add test for a direct reference install
  tests/data/install/pip-tools_direct_reference/micropipenv-0.0.0.tar.gz
  tests/test_micropipenv.py
Labels: size/S

#107 Version 0.5.0
  CHANGELOG.md
  micropipenv.py
Labels: approved, size/S

#110 Print pip version to logs in a test session
  tests/conftest.py
Labels: size/XS

#109 Mark online tests with a pytest.mark.online
  pytest.ini
  tests/conftest.py
  tests/test_micropipenv.py
Labels: size/M

#111 Add OWNERS file for Prow
  OWNERS
Labels: size/S

#114 Add pip version compatibility check
  micropipenv.py
  tests/test_micropipenv.py
Labels: approved, size/S
