Repository thoth-station/micropipenv, pull requests merged in 2021-12, with the labels that each got.

#210 Fix typo in an error message reported
  micropipenv.py
Labels: approved, size/XS

#214 Implement warning to make users aware of the missing check
  micropipenv.py
Labels: size/M

#212 Add Python 3.10 to trove classifiers
  setup.py
Labels: approved

#211 Version 1.2.0
  CHANGELOG.md
  micropipenv.py
Labels: approved, size/S

#213 Use setup.cfg
  setup.cfg
  setup.py
Labels: approved, size/M
