Repository thoth-station/micropipenv, pull requests merged in 2021-10, with the labels that each got.

#194 Skip markers
  micropipenv.py
  tests/data/parse/poetry_markers_skip/Pipfile.lock
  tests/data/parse/poetry_markers_skip/poetry.lock
  tests/data/parse/poetry_markers_skip/pyproject.toml
  tests/test_micropipenv.py
Labels: size/XL, approved

#196 Version 1.1.2
  CHANGELOG.md
  micropipenv.py
Labels: approved, size/S

#197 Fix missing subcommand in the README
  README.rst
Labels: approved, size/XS
