Repository thoth-station/micropipenv, pull requests merged in 2021-06, with the labels that each got.

#179 Adjust copyright in headers
  micropipenv.py
  tests/conftest.py
  tests/test_micropipenv.py
Labels: approved, size/XS

#180 Set development status trove classifier to production/stable
  setup.py
Labels: approved, size/XS

#178 Add resolving enviroment variables in Pipfile URL.
  micropipenv.py
  tests/data/install/pipenv_env_vars/Pipfile
  tests/data/install/pipenv_env_vars/Pipfile.lock
  tests/data/install/pipenv_env_vars_default/Pipfile
  tests/data/install/pipenv_env_vars_default/Pipfile.lock
  tests/test_micropipenv.py
Labels: ok-to-test, size/L

#181 Version 1.1.0
  CHANGELOG.md
  micropipenv.py
Labels: approved, size/S

#182 Test with pip==21.1.3
  micropipenv.py
Labels: approved, size/XS
