Repository thoth-station/micropipenv, pull requests merged in 2021-01, with the labels that each got.

#150 Add a link to Bodhi
  README.rst
Labels: approved, size/XS

#152 State how to enable micropipenv in s2i container images
  README.rst
Labels: approved, size/S

#153 Test with pip==21.0
  micropipenv.py
Labels: approved, size/XS

#154 Migrate CI from Travis to Github Actions
  .github/workflows/main.yml
  .travis.yml
  tox.ini
Labels: approved, size/L
