Repository thoth-station/micropipenv, pull requests merged in 2023-02, with the labels that each got.

#258 Bump supported pip version
  micropipenv.py
Labels: approved, size/XS, lgtm

#259 Define a [tests] extra and use it in tox
  setup.cfg
  tox.ini
Labels: approved, size/S, lgtm, ok-to-test

#257 Return full pipfile_entry dict instead of cherry-picking values
  micropipenv.py
  tests/data/requirements/vcs_ref_editable/requirements_only_direct.txt
  tests/test_micropipenv.py
Labels: approved, size/S, lgtm

#262 New release 1.4.6
  CHANGELOG.md
  micropipenv.py
Labels: size/S, lgtm

#263 Opt out as reviewers for micropipenv
  OWNERS
Labels: approved, size/XS
